---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "spring-server-service"
  namespace: "dev"
  labels:
    app: "spring-server"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "spring-server"
  type: "LoadBalancer"
  loadBalancerIP: "34.89.228.29"